- Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift
- Sources/SwiftLayout/Constraint/ConstraintLayout.swift
- Sources/SwiftLayout/Constraint/Protocol/ConstraintCreating.swift
- Sources/SwiftLayout/Layout/Extension/UIView+Layout.swift
- Sources/SwiftLayout/Layout/Layouts/OptionalLayout.swift
- Sources/SwiftLayout/Layout/Protocol/Layout.swift
- Sources/SwiftLayout/Layout/Protocol/LayoutContainable.swift
- Sources/SwiftLayout/Layout/Protocol/LayoutViewContainable.swift
- Tests/SwiftLayoutTests/ConstraintTests.swift
> Constraint의 활성화 순서를 UIView의 계층 구조 완료후로 개선

- Sources/SwiftLayout/Constraint/ConstraintLayout.swift
- Tests/SwiftLayoutTests/ConstraintTests.swift
Layout이 Costraint의 하부 구조에 포함될때 constraint가 제대로 생성이 안되는 버그 수정
> Constraint 버그 수정

- Sources/SwiftLayout/Constraint/ConstraintLayout.swift
- Sources/SwiftLayout/Layout/Extension/Layout+Description.swift
- Sources/SwiftLayout/Layout/Extension/Optional+Layout.swift
- Sources/SwiftLayout/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayout/Layout/Protocol/ContainableLayout.swift
- Sources/SwiftLayout/Layout/Protocol/ViewContainableLayout.swift
- 특정 기능을 가진 layout임에도 불구하고 Layout이 이름에 선행되어 일부 오해의 여지가 있어 수정
> 프로토콜 명칭 개선

- Sample/SwiftLayoutSample/SwiftLayoutSample/LayoutHostingViewController.swift
- Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift
- Sources/SwiftLayout/Building/LayoutBuilding.swift
- Sources/SwiftLayout/Layout/Layouts/Activation.swift
- Sources/SwiftLayout/Layout/Layouts/AnyDeactivatable.swift
- Sources/SwiftLayout/Layout/Protocol/Deactivatable.swift
- Sources/SwiftLayout/Layout/Protocol/Layout.swift
- Tests/SwiftLayoutTests/AnchorsTests.swift
- Tests/SwiftLayoutTests/DSLTests.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
- Tests/SwiftLayoutTests/LayoutViewTreeTests.swift
- for remove `AssociatedObject` and give the user permission to deactivate
- Need to think about how to give users permission to animations and changing layout
> add Deactivatable protocol

- Sources/SwiftLayout/Anchors/AnchorsLayout.swift
- Sources/SwiftLayout/Layout/Extension/Optional+Layout.swift
- Sources/SwiftLayout/Layout/Extension/UIView+Layout.swift
- Sources/SwiftLayout/Layout/Layouts/Deactivation.swift
- Sources/SwiftLayout/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayout/Layout/Protocol/ContainableLayout.swift
- Sources/SwiftLayout/Layout/Protocol/Layout.swift
Reverts ioskrew/SwiftLayout#55 #56
> Revert "hiding private features in Layout protocol"

- Sample/SwiftLayoutSample/SwiftLayoutSample/ViewController.swift
- Sources/SwiftLayout/Building/LayoutBuilding.swift
- Sources/SwiftLayout/Layout/Deactivation.swift
- Sources/SwiftLayout/Layout/Extension/Optional+Layout.swift
- Sources/SwiftLayout/Layout/Extension/UIView+Layout.swift
- Sources/SwiftLayout/Layout/Layouts/AnchorsLayout.swift
- Sources/SwiftLayout/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayout/Layout/Layouts/ViewPair.swift
- Sources/SwiftLayout/Layout/Protocol/Layout.swift
- Sources/SwiftLayout/Layout/Protocol/ViewContainable.swift
- Sources/SwiftLayout/Util/WeakReference.swift
- Tests/SwiftLayoutTests/DSLTests.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
> Layout animation

- Sources/SwiftLayout/Layout/Implementation/Activator.swift
- for constraint exceptions etc...
> - identifying before constraint process

- Sources/SwiftLayout/Layout/Implementation/Activator.swift
- Code cleanup﻿
- Add assertion when root view cannot be found while using LayoutOptions.accessibilityIdentifiers option
> Activator code improvement

- Sources/SwiftLayout/Components/Anchors/Anchors.swift
- Sources/SwiftLayout/Components/Anchors/Constraint.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
> Add setMultiplier method to anchor

- Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
- Sources/SwiftLayout/Components/Activator/Deactivation.swift
- Sources/SwiftLayout/Components/Layout/Layout.swift
- Sources/SwiftLayout/Components/Layout/ViewInformation.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
- Tests/SwiftLayoutTests/LayoutDSLTest.swift
> this pr absolutely inspired by Combine
- now Layout.active() return AnyDeactivable
- update test cases
- its for control multiple layout in use case
> anydeactivable

- README.md
- Sources/SwiftLayout/Components/Activator/Activator.swift
- Sources/SwiftLayout/Components/Anchors/Anchors.swift
- Sources/SwiftLayout/Components/Anchors/Constraint.swift
- Sources/SwiftLayout/Components/Layout/Layout.swift
- Tests/SwiftLayoutTests/AnchorsDSLTest.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
- Tests/SwiftLayoutTests/LayoutBuildingTest.swift
- Tests/SwiftLayoutTests/LayoutDSLTest.swift
- Tests/SwiftLayoutTests/PrintingTests.swift
- Tests/SwiftLayoutTests/Util/Extensions.swift
- anchor attributes extract from dummy view
- - remove LayoutAnchor - using concrete types of NSLayoutAnchor
- add finalActive to Activator
> add final active

- Sources/SwiftLayout/Components/Activator/Activator.swift
> simple bug fix

- Sources/SwiftLayout/Util/IdentifierUpdater.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
find properties for inheritance situation
> find property identifier on inheritances

- Sources/SwiftLayout/Components/Activator/Activator.swift
- Sources/SwiftLayout/Components/Layout/Layout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayout/Extension/UIVIew+Layout.swift
- Tests/SwiftLayoutTests/LayoutDSLTest.swift
- remove duplicates in activating
- its fix sublayout constraint traversing after config and anchors
> update traverse logics for empty layout and UIView

- Sources/SwiftLayout/Components/Activator/Activator.swift
- Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
- Sources/SwiftLayout/Components/Activator/Deactivation.swift
- Sources/SwiftLayout/Components/Layout/ViewInformation.swift
- Sources/SwiftLayout/Util/WeakReference.swift
- Tests/SwiftLayoutTests/AnchorsDSLTest.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
- Tests/SwiftLayoutTests/LayoutDSLTest.swift
- Tests/SwiftLayoutTests/PrintingTests.swift
- update views
- add sorting for nslayoutconstraint
- update only new constraints
- prevent animation of view for newly added to superview
https://user-images.githubusercontent.com/3011832/155862197-e0c88f54-99d9-4311-9a27-cb1251e9fd23.mp4
> improve updating

- README.md
- Sources/SwiftLayout/Components/Activator/Activator.swift
- Sources/SwiftLayout/Components/Activator/AnyDeactivable.swift
- Sources/SwiftLayout/Components/Activator/Deactivation.swift
- Sources/SwiftLayout/Components/Builder/AnchorsBuilder.swift
- Sources/SwiftLayout/Components/Layout/Layout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/AnchorsLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/AnyLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/ArrayLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/ConditionalLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/EmptyLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/OptionalLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/SublayoutLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/TupleLayout.swift
- Sources/SwiftLayout/Components/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayout/Components/Layout/ViewInformation.swift
- Sources/SwiftLayout/Extension/Optional+Layout.swift
- Sources/SwiftLayout/Extension/UIVIew+Layout.swift
- Sources/SwiftLayout/Util/WeakReference.swift
- Tests/SwiftLayoutTests/AnchorsDSLTest.swift
- Tests/SwiftLayoutTests/ImplementationTest.swift
- Tests/SwiftLayoutTests/LayoutDSLTest.swift
- Tests/SwiftLayoutTests/PrintingTests.swift
after #116 
- update views
- add sorting for nslayoutconstraint
- update only new constraints
- prevent animation of view for newly added to superview
- refactoring add to superview
- test passed for finalActive()
- fix ordering of capture current frame
- update layout for animation
- update animation logic
- ViewInformaion.animate -> layoutIfPossible
- update traverse argument to ViewInformation
- deprecate animationDisabled
as a result
https://user-images.githubusercontent.com/3011832/155867532-74e10d3b-d92e-49cc-bc6a-acf9a00f0a70.mp4
> individual animation handler

- Sources/SwiftLayout/Components/Layout/Layouts/GroupLayout.swift
- Tests/SwiftLayoutTests/ImplementationTests.swift
- Tests/SwiftLayoutTests/LayoutDSLTests.swift
- for number of layout greater than 7
- add test case
> add GroupLayout

- Sources/SwiftLayout/Components/Activator/Deactivable.swift
- Sources/SwiftLayout/Components/Layout/Layout.swift
- Tests/SwiftLayoutTests/LayoutDSLTests.swift
It seems that the deactivable structure needs improvement.
> update layout without LayoutBuilding

- Tests/SwiftLayoutTests/ReferenceTests.swift
> using context function for reference test

- Sources/SwiftLayout/Components/Anchors/ConstraintableItem.swift
- Sources/SwiftLayout/Extension/Anchors/Anchors+Convenience.swift
```swift
self {
center.anchors {
Anchors.center()
}
}
```
> add center to Anchors

- Sources/SwiftLayout/Printing/SwiftLayoutPrinter.swift
- Tests/SwiftLayoutTests/ImplementationTests.swift
- Tests/SwiftLayoutTests/LayoutDSLTests.swift
- Tests/SwiftLayoutTests/PrintingTests.swift
> add options to SwiftLayoutPrinter

- Tests/SwiftLayoutTests/PerformanceTests.swift
- Tests/SwiftLayoutTests/View/NativeApiView.swift
- Tests/SwiftLayoutTests/View/SwiftLayoutView.swift
- Tests/SwiftLayoutTests/View/XibView.swift
- For comparing the performance of Native api and SwiftLayout
- There is a problem that the snapshot of NativeApiView is not normal
> add native api view test

- README.md
- README_ko.md
- add README_ko.md
- update README.md for changed feature
- first sample now be for logo
come koreans. this for you(and me).
> add README_ko.md

- Sources/SwiftLayout/Printing/Describe/Tag/ViewTags.swift
Reverts ioskrew/SwiftLayout#190
> Revert "ViewTags.tag to generic for prevent type erasing"

- Sources/SwiftLayout/Printing/Describe/Tag/ViewTags.swift
- Sources/SwiftLayout/Printing/Describe/Token/AnchorToken.swift
- Sources/SwiftLayout/Printing/Describe/Token/ViewToken.swift
Reverts ioskrew/SwiftLayout#189
> Revert "subscripts for any object call self in some conditions"

- Sources/SwiftLayoutUtil/IdentifierUpdater.swift
- Sources/SwiftLayoutUtil/ViewPrinter.swift
> improving for IdentifierUpdater

- Sources/SwiftLayout/Core/Anchors/Elements/AnchorsExpression.swift
- Tests/SwiftLayoutTests/AnchorsDSLTests.swift
- Tests/SwiftLayoutTests/ImplementationTests.swift
#211 
keeps following values in setting constant or multiplier
- toAttribute
- constant
- multiplier
> improving set constant and multiplier in Anchors

- Tests/SwiftLayoutTests/ImplementationTests/AnchorsImplementationTests.swift
- Tests/SwiftLayoutTests/InterfaceTests/AnchorsDSLTests.swift
- Tests/SwiftLayoutTests/InterfaceTests/LayoutDSLTests.swift
- Tests/SwiftLayoutTests/InterfaceTests/LayoutableTests.swift
- Tests/SwiftLayoutTests/Util/XCTViewAssert.swift
- Tests/SwiftLayoutTests/Util/XCTestCase+Context.swift
#213 
implementation test cases now has a solid, detailed and concrete structure by @gmlwhdtjd
so, we can now make more flexible api for DSL testing with layout API.
> improving testing

- Sources/SwiftLayoutUtil/Describe/Tag/ViewTags.swift
- Sources/SwiftLayoutUtil/Describe/Token/ViewToken.swift
- Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
- fix print only identifier option of view printer to enable
> fix only identifier option for view printer

- Sources/SwiftLayout/Core/Layout/ViewInformation.swift
UIStackView needs add subview before add arranged view for reordering.
- test passed
- bug fix
force merging
> fix arranged subview ordering in UIStackView

- Sources/SwiftLayoutUtil/Describe/ConfigurablePropertys/ConfigurableProperty.swift
- Sources/SwiftLayoutUtil/Describe/Describer/ViewDescriber.swift
- Tests/SwiftLayoutUtilTests/ViewPrinterTests.swift
- sorting default config properties by alphabetically
- update tests
> Config properties sorting

- Sources/SwiftLayout/Core/Layout/Layout.swift
- Sources/SwiftLayout/Core/Layout/LayoutElements.swift
- Sources/SwiftLayout/Core/Layout/LayoutExplorer.swift
- Sources/SwiftLayout/Core/Layout/LayoutOption.swift
- Sources/SwiftLayout/Core/Layout/Layouts/GroupLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayout/Core/Layout/ViewInformation.swift
- Tests/SwiftLayoutTests/ImplementationTests/ImplementationTests.swift
- Tests/SwiftLayoutTests/InterfaceTests/LayoutDSLTests.swift
> add LayoutOption - isNotArranged

- Sources/SwiftLayout/Core/Builder/LayoutBuilder.swift
- Sources/SwiftLayout/Core/Layout/Layouts/TupleLayout.swift
Relieve the maximum number of sub-items limit for sublayout method #249
From: 7
To: 10
sublayout {
item
item
item
...
item
}
I would like to review whether this function works well.
Thank you.
> Relieve the maximum number of sub-items limit for sublayout method

- README.md
- README_ko.md
- Sources/SwiftLayout/Core/Activator/Component/ViewInformation.swift
- Sources/SwiftLayout/Core/Layout/Layout.swift
- Sources/SwiftLayout/Core/Layout/LayoutExplorer.swift
- Sources/SwiftLayout/Core/Layout/Layouts/AnyLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/ArrayLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/ConditionalLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/GroupLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/ModularLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/OptionalLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/TupleLayout.swift
- Sources/SwiftLayout/Core/Layout/Layouts/ViewLayout.swift
- Sources/SwiftLayoutUtil/Describe/Tag/ViewTags.swift
- Sources/SwiftLayoutUtil/Extension/Configuration/Optional+Configuration.swift
- Tests/SwiftLayoutTests/ImplementationTests/ReferenceTests.swift
As it was decided to support Swift 5.7 only
- Updated README.md to guide the proper version of SwiftLayout based on Swift version
- Updated some code to match latest swift syntax
> Swift version update

- README.md
- README_ko.md
A PR that adds the contents of the readme updated in the meantime on the main branch to the develop branch.
> Readme updates
